package com.mycompany.parqueadero;
import java.util.Timer;
import java.util.TimerTask;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author julio
 */
public class Menu extends javax.swing.JFrame {
    
    DefaultTableModel modelo = new DefaultTableModel();
    ArrayList<Vehiculo> lista = new ArrayList();
    Vehiculo vehiculo[] = new Vehiculo[10000]; 
    int num_vehiculo = 0;
    LocalDateTime tiempo;
    private String Ceros(int t) {
        if(t<10)
            return "0";
        return "";
    }
    public int valor$(String Tipo_V){
        if("Bicicleta y Ciclomotores".equals(Tipo_V))
            return 20;
        if("Carro".equals(Tipo_V))
            return 60;
        return 30;     
    }
    public void Llenar_Tabla(){
         ArrayList<Object> categ = new ArrayList<>();
         categ.add("# Vehículo");
         categ.add("Placa");
         categ.add("Tipo Vehículo");
         categ.add("Hora Ingreso");
         categ.add("Valor a Pagar");
         for(Object columna : categ){
             modelo.addColumn(columna);
         }
         this.Tabla.setModel(modelo);         
    }
    public void Fill_Rows(int ruedas){
        while(Tabla.getRowCount() > 0){
            modelo.removeRow(0);
        }
        ArrayList<Object[]> datos = new ArrayList<>();        
        for (int c = 0; c < lista.size(); c++) {
            if(ruedas == 0){
                datos.add(new Object[]{lista.get(c).getNum_vehiculo(), lista.get(c).getPlaca(), lista.get(c).getTipo_v(),
                        lista.get(c).getHora() + ":" + lista.get(c).getMinutos(),
                        "$" + lista.get(c).Minutos_Pagar() * valor$(lista.get(c).getTipo_v())});
            }else{   
                if(lista.get(c).Num_rueda() == ruedas ){
                    datos.add(new Object[]{lista.get(c).getNum_vehiculo(), lista.get(c).getPlaca(), lista.get(c).getTipo_v(),
                        lista.get(c).getHora() + ":" + lista.get(c).getMinutos(),
                        "$" + lista.get(c).Minutos_Pagar() * valor$(lista.get(c).getTipo_v())});
                }
            }
        }
        for(Object[] info  : datos){
            modelo.addRow(info);         
        } 
    }
    
    public Menu() {
        initComponents();
        Llenar_Tabla();
        num_vehiculo = 0;
        Timer timer = new Timer();
        TimerTask hora = new TimerTask() {
            @Override
            public void run() {
                tiempo = LocalDateTime.now();
                Hora.setText(Ceros(tiempo.getHour()) + "" + tiempo.getHour() + ":" + Ceros(tiempo.getMinute()) + "" + tiempo.getMinute());
            }
        };
        timer.scheduleAtFixedRate(hora, 10, 10);
        Placa.setVisible(false);
        Tipo_V.setVisible(false);
        num_vehiculo_label.setVisible(false);
        Placa_Label.setVisible(false);
        Tipo_v_Label.setVisible(false);
        Registrar.setVisible(false);     
        Auxiliar.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Ingreso = new javax.swing.JButton();
        Ver_Tabla = new javax.swing.JButton();
        V_4_R = new javax.swing.JButton();
        V_2_R = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Tipo_V = new javax.swing.JComboBox<>();
        Placa = new javax.swing.JTextField();
        Placa_Label = new javax.swing.JLabel();
        Tipo_v_Label = new javax.swing.JLabel();
        num_vehiculo_label = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        Registrar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Auxiliar = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        Ingreso.setBackground(new java.awt.Color(102, 102, 102));
        Ingreso.setForeground(new java.awt.Color(51, 51, 51));
        Ingreso.setText("Ingreso Vehículo");
        Ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresoActionPerformed(evt);
            }
        });

        Ver_Tabla.setBackground(new java.awt.Color(102, 102, 102));
        Ver_Tabla.setForeground(new java.awt.Color(51, 51, 51));
        Ver_Tabla.setText("Visualizar Tabla");
        Ver_Tabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver_TablaActionPerformed(evt);
            }
        });

        V_4_R.setBackground(new java.awt.Color(102, 102, 102));
        V_4_R.setForeground(new java.awt.Color(51, 51, 51));
        V_4_R.setText("Vehículos 4 Ruedas");
        V_4_R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V_4_RActionPerformed(evt);
            }
        });

        V_2_R.setBackground(new java.awt.Color(102, 102, 102));
        V_2_R.setForeground(new java.awt.Color(51, 51, 51));
        V_2_R.setText("Vehículos 2 Ruedas");
        V_2_R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V_2_RActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Total Vehículos/Pagar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Eliminar.setBackground(new java.awt.Color(102, 102, 102));
        Eliminar.setForeground(new java.awt.Color(51, 51, 51));
        Eliminar.setText("Eliminar Vehículo");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Salir.setBackground(new java.awt.Color(102, 102, 102));
        Salir.setForeground(new java.awt.Color(51, 51, 51));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        Tipo_V.setBackground(new java.awt.Color(204, 204, 204));
        Tipo_V.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carro", "Moto", "Bicicleta y Ciclomotores" }));

        Placa.setBackground(new java.awt.Color(153, 153, 153));
        Placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlacaActionPerformed(evt);
            }
        });

        Placa_Label.setText("Placa");

        Tipo_v_Label.setText("Tipo de Vehículo");

        num_vehiculo_label.setText("# Vehículo: 1");

        Hora.setText("jLabel1");

        Registrar.setBackground(new java.awt.Color(102, 102, 102));
        Registrar.setText("Registrar");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(Tabla);

        Auxiliar.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Placa, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(Placa_Label)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Tipo_V, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Tipo_v_Label)
                                .addGap(77, 77, 77)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Registrar)
                            .addComponent(num_vehiculo_label))
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Ver_Tabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Eliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ingreso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(V_2_R, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(V_4_R, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Hora)
                .addGap(65, 65, 65))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(Salir)
                        .addGap(52, 52, 52)
                        .addComponent(Auxiliar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Hora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ingreso)
                    .addComponent(V_2_R))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Eliminar)
                    .addComponent(V_4_R))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ver_Tabla)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tipo_V, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num_vehiculo_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Placa_Label)
                        .addComponent(Tipo_v_Label))
                    .addComponent(Registrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salir)
                    .addComponent(Auxiliar))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ver_TablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver_TablaActionPerformed
        Fill_Rows(0);        
        Tabla.setModel(modelo);
        Auxiliar.setVisible(false);
    }//GEN-LAST:event_Ver_TablaActionPerformed

    private void V_4_RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V_4_RActionPerformed
        Fill_Rows(4);
        Tabla.setModel(modelo);
        Auxiliar.setVisible(false);
    }//GEN-LAST:event_V_4_RActionPerformed

    private void V_2_RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V_2_RActionPerformed
        Tabla.setModel(modelo);
        Auxiliar.setVisible(false);
        Fill_Rows(2);
    }//GEN-LAST:event_V_2_RActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int total_pagos = 0;
        for(int c = 0; c < lista.size(); c++){
            total_pagos += (lista.get(c).Minutos_Pagar() * valor$(lista.get(c).getTipo_v()));
        }
        Auxiliar.setText("Numero de vehículos: " +  lista.size() + "   Total pagos: $" + total_pagos );
        Auxiliar.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlacaActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void IngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresoActionPerformed
        Placa.setVisible(true);
        Tipo_V.setVisible(true);
        Registrar.setVisible(true);
        num_vehiculo_label.setVisible(true);
        Registrar.setText("Registrar");
        Auxiliar.setVisible(false);
    }//GEN-LAST:event_IngresoActionPerformed

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        if("Registrar".equals(Registrar.getText())){
            num_vehiculo++;
            vehiculo[num_vehiculo-1] = new Vehiculo(tiempo.getHour(),tiempo.getMinute(),Placa.getText(),Tipo_V.getSelectedItem().toString(),num_vehiculo);
            num_vehiculo_label.setText("# Vehículo: " + num_vehiculo);
            Tipo_V.setVisible(false);
            num_vehiculo_label.setVisible(false);
            lista.add(vehiculo[num_vehiculo-1]);
        }else{
            for(int c = 0; c < lista.size(); c++){
                if(lista.get(c).getPlaca().equals(Placa.getText()))
                    lista.remove(c);
            }         
        }
        Registrar.setVisible(false);
        Placa.setVisible(false);
        Placa_Label.setVisible(false);
        Placa.setText("");
    }//GEN-LAST:event_RegistrarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        Placa_Label.setVisible(true);
        Placa.setVisible(true);      
        Registrar.setText("Eliminar");
        Registrar.setVisible(true);
        Auxiliar.setVisible(false);
    }//GEN-LAST:event_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Auxiliar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JLabel Hora;
    private javax.swing.JButton Ingreso;
    private javax.swing.JTextField Placa;
    private javax.swing.JLabel Placa_Label;
    private javax.swing.JButton Registrar;
    private javax.swing.JButton Salir;
    private javax.swing.JTable Tabla;
    private javax.swing.JComboBox<String> Tipo_V;
    private javax.swing.JLabel Tipo_v_Label;
    private javax.swing.JButton V_2_R;
    private javax.swing.JButton V_4_R;
    private javax.swing.JButton Ver_Tabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel num_vehiculo_label;
    // End of variables declaration//GEN-END:variables
}
